const User = require('./user')

const newPerson1 = new User("Rick",55,6,5)
const newPerson2 = new User("Shari",38,7,3)


console.log("***newPerson1***")
// console.log(newPerson1.userAge)
// console.log(newPerson1.dataType(newPerson1.userAge))
newPerson1.num1 = newPerson1.turnNumberToString(newPerson1.num1)
// console.log(newPerson1.turnNumberToString(newPerson1.num1))
// console.log(newPerson1.dataType(newPerson1.turnNumberToString()))
newPerson1.num2 = newPerson1.turnNumberToString(newPerson1.num2)
console.log(newPerson1.nameAge())
console.log(newPerson1.addBy())
console.log(newPerson1.subtractBy())
console.log(newPerson1.multiplyBy())
console.log(newPerson1.divideBy())


console.log("***newPerson2***")
/* console.log(newPerson2.userAge)
console.log(newPerson2.dataType(newPerson2.userAge))
 */// console.log(newPerson2.turnNumberToString(newPerson2.num2))
newPerson2.num1 = newPerson2.turnNumberToString(newPerson2.num1)
// console.log(newPerson2.dataType(newPerson2.turnNumberToString()))
newPerson2.num2 = newPerson2.turnNumberToString(newPerson2.num2)
// console.log(newPerson2.turnNumberToString(newPerson2.num1))
console.log(newPerson2.nameAge())
console.log(newPerson2.addBy())
console.log(newPerson2.subtractBy())
console.log(newPerson2.multiplyBy())
console.log(newPerson2.divideBy())
